name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Frontend
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t frontend:latest ./frontend

      - name: Restart Frontend Container
        run: docker-compose up -d frontend
