name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f /home/ubuntu/chat-app/frontend/_work/chat_app_frontend/chat_app_frontend/Dockerfile ]; then
            echo "ERROR: Dockerfile not found!"
            exit 1
          fi
          echo "Dockerfile found ✓"

      - name: Stop and Clean Old Containers
        run: |
          cd /home/ubuntu/chat-app
          docker-compose down frontend || true
          docker image prune -f

      - name: Build and Deploy Frontend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache frontend
          docker-compose up -d frontend

      - name: Verify Deployment
        run: |
          sleep 15
          docker ps | grep frontend
          docker logs $(docker ps -q -f name=frontend) --tail 100
