name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Complete Frontend Cleanup
        run: |
          cd /home/ubuntu/chat-app
          docker-compose stop frontend 2>/dev/null || true
          docker rm -f chat-app_frontend_1 2>/dev/null || true
          docker rmi -f chat-app_frontend 2>/dev/null || true
          docker container prune -f
          docker image prune -f

      - name: Build Frontend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache frontend

      - name: Deploy Frontend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose up -d --force-recreate frontend

      - name: Verify Deployment
        run: |
          sleep 15
          docker ps | grep frontend
          docker logs chat-app_frontend_1 --tail 100
