name: Frontend CD

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 20
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Network Exists
        run: docker network create chat-app_default 2>/dev/null || true

      - name: Stop and Remove Old Frontend
        run: |
          docker stop chat-app_frontend_1 2>/dev/null || true
          docker rm -f chat-app_frontend_1 2>/dev/null || true
          docker rmi -f chat-app_frontend 2>/dev/null || true

      - name: Build Frontend
        run: |
          cd /home/ubuntu/chat-app
          docker-compose build --no-cache frontend

      - name: Ensure Dependencies Running
        run: |
          if ! docker ps | grep -q chat-app_backend_1; then
            echo "⚠️ Backend not running, starting it..."
            docker start chat-app_backend_1 || true
            sleep 5
          fi

      - name: Deploy Frontend
        run: |
          docker run -d \
            --name chat-app_frontend_1 \
            --network chat-app_default \
            -p 3000:3000 \
            --env-file /home/ubuntu/chat-app/frontend/.env.prod \
            --restart unless-stopped \
            chat-app_frontend

      - name: Verify Deployment
        run: |
          sleep 15
          docker ps | grep frontend
          docker logs chat-app_frontend_1 --tail 100
