name: Frontend CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend Container
        run: |
          cd /home/ubuntu/chat-app
          docker-compose down
          docker-compose up -d --build frontend
