name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd /home/ubuntu/chat-app/frontend/_work/chat_app_frontend/chat_app_frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps --force
