name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Clean and Install Dependencies
        run: |
          cd /home/ubuntu/chat-app/frontend/_work/chat_app_frontend/chat_app_frontend
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps --force

      - name: Build Frontend with Memory Limit
        run: |
          cd /home/ubuntu/chat-app/frontend/_work/chat_app_frontend/chat_app_frontend
          NODE_OPTIONS="--max-old-space-size=2048" npm run build
        timeout-minutes: 10
